// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image5":
            case "Seed":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . c c . . . . . . . 
. . . . . . c 4 4 c . . . . . . 
. . . . . . c 4 4 c . . . . . . 
. . . . . . . c c . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "The eye":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........fffffffffff..........
........f11222222211f.........
.......f1122222222211f........
......f112225555522211f.......
.....f111225ff555522111f......
....f1111225ff5555221111f.....
....f1111225555555221111f.....
.....f11112255555221111f......
......f111122555221111f.......
.......f1111222221111f........
........f11111111111f.........
.........fffffffffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
            case "image2":
            case "Cup":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 5 5 . . 5 . . . 5 . . 5 5 . 
. . 5 9 5 5 6 5 . 5 6 5 5 9 5 . 
. . . 5 9 6 7 b 7 b 7 6 9 5 . . 
. . . . 5 9 6 7 b 7 6 9 5 . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . . 5 9 6 9 5 . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . 5 5 5 5 5 . . . . . 
`;
            case "image3":
            case "myImage":return img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c b b b b b b c b b c c c . . 
. c 1 b b b 1 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b c b b b c b b b b f . . . . 
f b 1 f f f 1 b b b b f c . . . 
f b b b b b b b b b b f c c . . 
. f b b b b b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`;
            case "image4":
            case "Power":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . 4 . . . . . . . 
. . . . . . 3 3 4 4 4 . . . . . 
. . . . . 4 3 3 2 1 1 4 . . . . 
. . . . 4 3 3 3 2 2 5 4 4 . . . 
. . . . 4 4 3 2 4 4 4 4 4 . . . 
. . . . 4 2 3 2 4 4 4 4 4 . . . 
. . . . . 4 2 3 4 4 2 4 . . . . 
. . . . . . 2 2 2 2 2 . . . . . 
. . . . . . . . 4 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image7":
            case "bat":return img`
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . a a . . . . 
. . . a 5 5 a . . . 
. . . a 5 5 a . . . 
. . . . a a . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
`;
            case "image1":
            case "soldier":return img`
......dddd...........
....ddd22ddd.........
...ddd2222ddd........
..ddd111111ddd.......
..dd122222211d.......
..d12dddddd21d.......
..dddd1111dddd.......
.dd1dbf44fbd1dd......
.d1141fddf1411d......
..d11dddddd11d.......
...d11444411d........
..146bbbbbb641.......
..4d6bbbbbb6d4.......
..446445544644.......
.....666666..........
.....66..66..........
.....................
.....................
.....................
.....................
.....................
`;
            case "image8":
            case "Va":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. f f f f f . . . . . f f f f . 
. . f 1 1 f . . . . f f 1 1 1 f 
. . f 1 1 f . . . . f 1 1 1 1 f 
. . f 1 1 f f . . f f 1 1 1 1 f 
. . f 1 1 1 f . . f 1 1 1 1 1 f 
. . . f 1 1 1 f f f 1 1 1 1 1 f 
. . . f 1 1 1 f f 1 1 1 1 1 f . 
. . . . f 1 1 1 f 1 1 1 1 1 f . 
. . . . f f 1 1 1 1 1 1 1 f . . 
. . . . . f 1 1 1 1 1 1 f f . . 
. . . . . f f 1 1 1 f f f . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . . f . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image9":
            case "Idsd":return img`
. . . . . f f f f f f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 f f . . . . . 
. . . . . . f 1 1 f f . . . . . 
. . . . . . f 1 f f f . . . . . 
. . . . . . f f f f f . . . . . 
`;
            case "image10":
            case "Cds":return img`
. . . . f f f f f f f f f . . . 
. . . f f 1 1 1 1 1 1 1 f f . . 
. . . f 1 1 1 1 1 1 1 1 1 f . . 
. . . f 1 1 1 1 1 1 1 1 f f . . 
. . . f 1 1 1 1 1 f f f f . . . 
. . . f 1 1 1 f f f . . . . . . 
. . . f 1 1 f f . . . . . . . . 
. . . f 1 1 f f . . . . . . . . 
. . . f 1 1 1 f . . . . . . . . 
. . . f 1 1 1 f . . . . . . . . 
. . . f 1 1 1 f f . . . . . . . 
. . . f 1 1 1 1 f f f . . . . . 
. . . f 1 1 1 1 1 1 f f f . . . 
. . . f f 1 1 1 1 1 1 1 f f . . 
. . . . f f 1 1 1 1 1 1 1 f . . 
. . . . . f f f f f f f f f . . 
`;
            case "image11":
            case "Tdsd":return img`
. . f f f f f f f f f f f . . . 
. . f 1 1 1 1 1 1 f f 1 f . . . 
. . f 1 1 1 1 1 1 1 1 1 f f . . 
. f 1 1 1 1 1 1 1 1 1 1 1 f . . 
. f f f f f f 1 1 f f 1 1 f . . 
. . . . . . . f 1 1 f f f f . . 
. . . . . . . f 1 1 f . . . . . 
. . . . . . f f 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 f . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image12":
            case "Òdf":return img`
. . . . . f f f f f f f f . . . 
. . . . f f 1 1 1 1 1 1 f . . . 
. . . f f 1 1 1 1 1 1 1 1 f . . 
. . f f 1 1 1 1 1 1 1 1 1 f . . 
. . f 1 1 1 1 1 f f f 1 1 f . . 
. f 1 1 1 1 1 f f . f 1 1 1 f . 
. f 1 1 1 1 f f . . f 1 1 1 f . 
f f 1 1 1 1 f . . . f 1 1 1 f . 
f 1 1 1 1 1 f . . . f 1 1 1 f . 
f 1 1 1 1 1 f f f f f 1 1 1 f . 
f 1 1 1 1 1 1 1 1 1 1 1 1 1 f . 
. f 1 1 1 1 1 1 1 1 1 1 1 f . . 
. f f 1 1 1 1 1 1 1 1 1 1 f . . 
. . f f f 1 1 1 1 1 1 1 f f . . 
. . . . . f f f f f f f . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":
            case "Rfdf":return img`
. . . f f f f . . . . . . . . . 
. . . f 1 1 f f f f f . . . . . 
. . . f 1 1 1 1 1 1 f . . . . . 
. . . f 1 f f 1 1 1 f f . . . . 
. . f f 1 f f 1 f f f f . . . . 
. . f 1 1 1 1 1 f . . . . . . . 
. . f 1 1 f 1 1 1 f . . . . . . 
. f f 1 f f f 1 1 f . . . . . . 
. f 1 1 f . f f 1 f . . . . . . 
. f 1 f . . . f 1 1 f . . . . . 
. f 1 f . . . f 1 1 f f . . . . 
. f f f . . . f 1 1 1 f f . . . 
. f f f . . . f 1 1 1 1 f . . . 
. . . . . . . f f f f f f . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image18":
            case "C":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . d d d d . . . . . 
. . . . . . d b b b b d . . . . 
. . . . . d b d c c c d . . . . 
. . . . . d b c . . . . . . . . 
. . . . . d b c . . . . . . . . 
. . . . . d b c . . . . . . . . 
. . . . . d b c . . . . . . . . 
. . . . . d b d c c c d . . . . 
. . . . . . d b b b b d . . . . 
. . . . . . . d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image20":
            case "O":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . d d d d . . . . . . 
. . . . . d b b b b d . . . . . 
. . . . d b c 6 6 c b d . . . . 
. . . . d b 6 . . 6 b d . . . . 
. . . . d b 6 . . 6 b d . . . . 
. . . . d b 6 . . 6 b d . . . . 
. . . . d b 6 . . 6 b d . . . . 
. . . . d b c 6 6 c b d . . . . 
. . . . . d b b b b d . . . . . 
. . . . . . d d d d . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image17":
            case "I":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . d d d d d d d . . . . 
. . . . . d b 6 6 6 b d . . . . 
. . . . . . d b 6 b d . . . . . 
. . . . . . . b 6 b . . . . . . 
. . . . . . . d 6 d . . . . . . 
. . . . . . . d 6 d . . . . . . 
. . . . . . . d 6 d . . . . . . 
. . . . . . . b 6 b . . . . . . 
. . . . . . d b 6 b d . . . . . 
. . . . . d b 6 6 6 b d . . . . 
. . . . . d d d d d d d . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image21":
            case "R":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . d d d . . . . . . . 
. . . . . d b b b d . . . . . . 
. . . . . d b . . b d . . . . . 
. . . . . d b . . . b d . . . . 
. . . . . d b . . . b d . . . . 
. . . . . d b . b d d . . . . . 
. . . . . d b b d . . . . . . . 
. . . . . d b . b d . . . . . . 
. . . . . d b . . b d . . . . . 
. . . . . d b . . . b d . . . . 
. . . . . d d . . . . b d . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image14":
            case "V":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . d d d . . . d d d . . . 
. . . . d 6 b . . . b 6 d . . . 
. . . . d 6 b . . . b 6 d . . . 
. . . . d 6 b . . . b 6 d . . . 
. . . . . d 6 b . b 6 d . . . . 
. . . . . d 6 b . b 6 d . . . . 
. . . . . . d 6 b 6 d . . . . . 
. . . . . . . d 6 d . . . . . . 
. . . . . . . . d . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image19":
            case "T":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . d d d d d d d d d . . . 
. . . . d b b c c c b b d . . . 
. . . . . d b b c b b d . . . . 
. . . . . . . d c d . . . . . . 
. . . . . . . d c d . . . . . . 
. . . . . . . d c d . . . . . . 
. . . . . . . d c d . . . . . . 
. . . . . . . d b d . . . . . . 
. . . . . . . d b d . . . . . . 
. . . . . . . d d d . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "SL":
            case "anim6":return [img`
.............ccfff..............
...........ccddbcf..............
..........ccddbbf...............
..........fccbbcf...............
.....fffffccccccff.........ccc..
...ffbbbbbbbcbbbbcfff....ccbbc..
..fbbbbbbbbcbcbbbbcccff.cdbbc...
ffbbbbbbffbbcbcbbbcccccfcdbbf...
fbcbbb112f1bcbbbbbcccccffbbf....
fbbb11111111bbbbbcccccccbbcf....
.fb11133cc11bbbbcccccccccccf....
..fccc31c211bbbcccccbdbffbbcf...
...fc13c111cbbbfcddddcc..fbbf...
....fccc111fbdbbccdcc.....fbbf..
........ccccfcdbbcc........fff..
.............fffff..............
`, img`
.............ccfff..............
............cddbbf..............
...........cddbbf...............
..........fccbbcf............ccc
....ffffffccccccff.........ccbbc
..ffbbbbbbbbbbbbbcfff.....cdbbc.
ffbbbbbbbbbcbcbbbbcccff..cddbbf.
fbcbbbbbffbbcbcbbbcccccfffdbbf..
fbbb11112f1bcbcbbbcccccccbbbcf..
.fb11111111bbbbbbcccccccccbccf..
..fccc33cc11bbbbccccccccfffbbcf.
...fc131c211bbbcccccbdbc...fbbf.
....f33c111cbbbfdddddcc.....fbbf
.....ff1111fbdbbfddcc........fff
.......cccccfbdbbfc.............
.............fffff..............
`, img`
..............cfff..............
............ccddbf..............
...........cbddbff.........ccc..
..........fccbbcf.........cbbc..
...fffffffccccccff.......cdbc...
.ffcbbbbbbbbbbbbbcfff....cdbf...
fcbbbbbbbbbcbbbbbbcccff.cdbf....
fbcbbbbffbbbcbcbbbcccccffdcf....
fbb11112fbbbcbcbbbccccccbbcf....
.fb11111111bbcbbbccccccccbbcf...
..fccc33cb11bbbbcccccccfffbbf...
...fc131c111bbbcccccbdbc..fbbf..
....f33c211cbbccdddddbc....fff..
.....ff1111fdbbccddbcc..........
.......cccccfdbbbfcc............
.............fffff..............
`, img`
.............ccfff..............
............cddbbf..............
...........cddbbf...............
..........fccbbcf............ccc
....ffffffccccccff.........ccbbc
..ffbbbbbbbbbbbbbcfff.....cdbbc.
ffbbbbbbbbbcbcbbbbcccff..cddbbf.
fbcbbbbbffbbcbcbbbcccccfffdbbf..
fbbb11112f1bcbcbbbcccccccbbbcf..
.fb11111111bbbbbbcccccccccbccf..
..fccc33cc11bbbbccccccccfffbbcf.
...fc131c111bbbcccccbdbc...fbbf.
....f33c211cbbbfdddddcc.....fbbf
.....ff1111fbdbbfddcc........fff
.......cccccfbdbbfc.............
.............fffff..............
`];
            case "SAL":
            case "anim8":return [img`
.................ccfff..............
................cddbbf..............
...............cddbbf...............
..............fccbbcf............ccc
........ffffffccccccff.........ccbbc
......ffbbbbbbbbbbbbbcfff.....cdbbc.
....ffbbbbbbbbbcbcbbbbcccff..cddbbf.
....fbcbbbbbffbbcbcbbbcccccfffdbbf..
....fbbb11112f1bcbcbbbcccccccbbbcf..
.....fb11111111bbbbbbcccccccccbccf..
......fccc33cc11bbbbccccccccfffbbcf.
.......fc131c211bbbcccccbdbc...fbbf.
........f33c111cbbbfdddddcc.....fbbf
.........ff1111fbdbbfddcc........fff
...........cccccfbdbbfc.............
.................fffff..............
`, img`
.................ccfff..............
................cddbbf..............
...............cddbbf...............
.........ffffffccbbcf...............
......fffbbbbbbbbcccff..............
.....fbbbbbbbbbbbbbbbcfff......ccccc
.....bcbbbbbffbcbcbbbbcccff...cdbbbc
.....bbb11112fbbcbcbbbcccccffcddbbc.
.....fb11111111bcbcbbbcccccccbdbbf..
......fccc33c11bbbbbbcccccccccbbcf..
.......fc131cc11bbbbccccccccffbccf..
........f33c2111bbbcccccbdbc..fbbcf.
.........ff1111cbbbfdddddcc....fbbf.
...........ccc1fbdbbfddcc.......fbbf
..............ccfbdbbfc..........fff
.................fffff..............
`, img`
..................ccfff.............
.................cddbbf.............
........fffffffffddbbf..............
.......fbbbbbbbbbfcbcf..............
.......fbbc111bffbbccffff...........
.......fb1111112fbbbbbcccff....ccccc
........f1cc3311bbcbcbbccccf..cdbbbc
........fcc131c1bbbcbcbcccccfcddbbc.
.........f111121bbbcbcbccccccbdbbf..
.........f1111111bbbbbccccccccbbcf..
..........f111111bbbbcccccccffbccf..
...........c1111cbbbcccccbdbc.fbbcf.
............cc11cbbbfddddddc...fbbf.
..............cffbdbbfdddcc.....fbbf
.................fbdbbfcc........fff
..................fffff.............
`, img`
....................ccfff...........
..........fffffffffcbbbbf...........
.........fbbbbbbbbbfffbf............
.........fbb111bffbbbbff............
.........fb111112fbbbbbcff..........
.........f1cccc11bbcbcbcccf.........
..........fc1c1c1bbbcbcbcccf...ccccc
............c3331bbbcbcbccccfccddbbc
...........c333c1bbbbbbbcccccbddbcc.
...........c331c11bbbbbcccccccbbcc..
..........cc13c211bbbbccccccffbccf..
..........c111111cbbbcccccbbc.fccf..
...........cc1111cbbbfdddddc..fbbcf.
.............cccffbdbbfdddc....fbbf.
..................fbdbbfcc......fbbf
...................fffff.........fff
`, img`
...........fffffff...ccfff..........
..........fbbbbbbbffcbbbbf..........
..........fbb111bbbbbffbf...........
..........fb11111ffbbbbff...........
..........f1cccc12fbbbbbcff.........
..........ffc1c1c1bbcbcbcccf........
...........fcc3331bbbcbcbcccf..ccccc
............c333c1bbbcbcbccccfcddbbc
............c333c1bbbbbbbcccccddbcc.
............c333c11bbbbbccccccbbcc..
...........cc331c11bbbbccccccfbccf..
...........cc13c21cbbbcccccbbcfccf..
...........c111111cbbbfdddddc.fbbcf.
............cc1111fbdbbfdddc...fbbf.
..............cccfffbdbbfcc.....fbbf
....................fffff........fff
`, img`
....................................
....................................
....................................
...............ccffff...............
..............cddbbbf...............
.......ffffffcddbbbf................
.....ffbbbbbbbbbbbbbcfff.......ccccc
...ffbbbbbbbbcbcbbbbbcccff....cdbbbc
..fbbbbbbbbbbcbbcbbbbcccccfffcddbbc.
.fbcbbbbbbbbbbcbcbbbbccccccccbdbbf..
.fbbbbbbbfffbbcbbbbbccccccccccbbcf..
.ffbb111122fbbcbbbbcccccccbcffbccf..
..ff111111111bbbbccccccbbbcc..fbbcf.
....ccccccc111bdbbbfddbccc.....ffbbf
........ccccccfbdbbbfcc..........fff
...............ffffff...............
`];
            case "SR":
            case "anim7":return [img`
..............fffcc.............
..............fcbddcc...........
...............fbbddcc..........
...............fcbbccf..........
..ccc.........ffccccccfffff.....
..cbbcc....fffcbbbbcbbbbbbbff...
...cbbdc.ffcccbbbbcbcbbbbbbbbf..
...fbbdcfcccccbbbcbcbbffbbbbbbff
....fbbffcccccbbbbbcb1f211bbbcbf
....fcbbcccccccbbbbb11111111bbbf
....fcccccccccccbbbb11cc33111bf.
...fcbbffbdbcccccbbb112c13cccf..
...fbbf..ccddddcfbbbc111c31cf...
..fbbf.....ccdccbbdbf111cccf....
..fff........ccbbdcfcccc........
..............fffff.............
`, img`
..............fffcc.............
..............fbbddc............
...............fbbddc...........
ccc............fcbbccf..........
cbbcc.........ffccccccffffff....
.cbbdc.....fffcbbbbbbbbbbbbbff..
.fbbddc..ffcccbbbbcbcbbbbbbbbbff
..fbbdfffcccccbbbcbcbbffbbbbbcbf
..fcbbbcccccccbbbcbcb1f21111bbbf
..fccbcccccccccbbbbbb11111111bf.
.fcbbfffccccccccbbbb11cc33cccf..
.fbbf...cbdbcccccbbb111c131cf...
fbbf.....ccdddddfbbbc111c33f....
fff........ccddfbbdbf1111ff.....
.............cfbbdbfccccc.......
..............fffff.............
`, img`
..............fffc..............
..............fbddcc............
..ccc.........ffbddbc...........
..cbbc.........fcbbccf..........
...cbdc.......ffccccccfffffff...
...fbdc....fffcbbbbbbbbbbbbbcff.
....fbdc.ffcccbbbbbbcbbbbbbbbbcf
....fcdffcccccbbbcbcbbbffbbbbcbf
....fcbbccccccbbbcbcbbbf21111bbf
...fcbbccccccccbbbcbb11111111bf.
...fbbfffcccccccbbbb11bc33cccf..
..fbbf..cbdbcccccbbb111c131cf...
..fff....cbdddddccbbc112c33f....
..........ccbddccbbdf1111ff.....
............ccfbbbdfccccc.......
..............fffff.............
`, img`
..............fffcc.............
..............fbbddc............
...............fbbddc...........
ccc............fcbbccf..........
cbbcc.........ffccccccffffff....
.cbbdc.....fffcbbbbbbbbbbbbbff..
.fbbddc..ffcccbbbbcbcbbbbbbbbbff
..fbbdfffcccccbbbcbcbbffbbbbbcbf
..fcbbbcccccccbbbcbcb1f21111bbbf
..fccbcccccccccbbbbbb11111111bf.
.fcbbfffccccccccbbbb11cc33cccf..
.fbbf...cbdbcccccbbb111c131cf...
fbbf.....ccdddddfbbbc112c33f....
fff........ccddfbbdbf1111ff.....
.............cfbbdbfccccc.......
..............fffff.............
`];
            case "SAR":
            case "anim9":return [img`
..............fffcc.................
..............fbbddc................
...............fbbddc...............
ccc............fcbbccf..............
cbbcc.........ffccccccffffff........
.cbbdc.....fffcbbbbbbbbbbbbbff......
.fbbddc..ffcccbbbbcbcbbbbbbbbbff....
..fbbdfffcccccbbbcbcbbffbbbbbcbf....
..fcbbbcccccccbbbcbcb1f21111bbbf....
..fccbcccccccccbbbbbb11111111bf.....
.fcbbfffccccccccbbbb11cc33cccf......
.fbbf...cbdbcccccbbb111c131cf.......
fbbf.....ccdddddfbbbc112c33f........
fff........ccddfbbdbf1111ff.........
.............cfbbdbfccccc...........
..............fffff.................
`, img`
..............fffcc.................
..............fbbddc................
...............fbbddc...............
...............fcbbccffffff.........
..............ffcccbbbbbbbbfff......
ccccc......fffcbbbbbbbbbbbbbbbf.....
cbbbdc...ffcccbbbbcbcbffbbbbbcb.....
.cbbddcffcccccbbbcbcbbf21111bbb.....
..fbbdbcccccccbbbcbcb11111111bf.....
..fcbbcccccccccbbbbbb11c33cccf......
..fccbffccccccccbbbb11cc131cf.......
.fcbbf..cbdbcccccbbb1112c33f........
.fbbf....ccdddddfbbbc1111ff.........
fbbf.......ccddfbbdbf1ccc...........
fff..........cfbbdbfcc..............
..............fffff.................
`, img`
.............fffcc..................
.............fbbddc.................
..............fbbddfffffffff........
..............fcbcfbbbbbbbbbf.......
...........ffffccbbffb111cbbf.......
ccccc....ffcccbbbbbf2111111bf.......
cbbbdc..fccccbbcbcbb1133cc1f........
.cbbddcfcccccbcbcbbb1c131ccf........
..fbbdbccccccbcbcbbb121111f.........
..fcbbccccccccbbbbb1111111f.........
..fccbffcccccccbbbb111111f..........
.fcbbf.cbdbcccccbbbc1111c...........
.fbbf...cddddddfbbbc11cc............
fbbf.....ccdddfbbdbffc..............
fff........ccfbbdbf.................
.............fffff..................
`, img`
...........fffcc....................
...........fbbbbcfffffffff..........
............fbfffbbbbbbbbbf.........
............ffbbbbffb111bbf.........
..........ffcbbbbbf211111bf.........
.........fcccbcbcbb11cccc1f.........
ccccc...fcccbcbcbbb1c1c1cf..........
cbbddccfccccbcbcbbb1333c............
.ccbddbcccccbbbbbbb1c333c...........
..ccbbcccccccbbbbb11c133c...........
..fccbffccccccbbbb112c31cc..........
..fccf.cbbcccccbbbc111111c..........
.fcbbf..cdddddfbbbc1111cc...........
.fbbf....cdddfbbdbffccc.............
fbbf......ccfbbdbf..................
fff.........fffff...................
`, img`
..........fffcc...fffffff...........
..........fbbbbcffbbbbbbbf..........
...........fbffbbbbb111bbf..........
...........ffbbbbff11111bf..........
.........ffcbbbbbf21cccc1f..........
........fcccbcbcbb1c1c1cff..........
ccccc..fcccbcbcbbb1333ccf...........
cbbddcfccccbcbcbbb1c333c............
.ccbddcccccbbbbbbb1c333c............
..ccbbccccccbbbbb11c333c............
..fccbfccccccbbbb11c133cc...........
..fccfcbbcccccbbbc12c31cc...........
.fcbbf.cdddddfbbbc111111c...........
.fbbf...cdddfbbdbf1111cc............
fbbf.....ccfbbdbfffccc..............
fff........fffff....................
`, img`
....................................
....................................
....................................
...............ffffcc...............
...............fbbbddc..............
................fbbbddcffffff.......
ccccc.......fffcbbbbbbbbbbbbbff.....
cbbbdc....ffcccbbbbbcbcbbbbbbbbff...
.cbbddcfffcccccbbbbcbbcbbbbbbbbbbf..
..fbbdbccccccccbbbbcbcbbbbbbbbbbcbf.
..fcbbccccccccccbbbbbcbbfffbbbbbbbf.
..fccbffcbcccccccbbbbcbbf221111bbff.
.fcbbf..ccbbbccccccbbbb111111111ff..
fbbff.....cccbddfbbbdb111ccccccc....
fff..........ccfbbbdbfcccccc........
...............ffffff...............
`];
            case "Eye Animation":
            case "anim16":return [img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........fffffffffff..........
........f11222222211f.........
.......f1122222222211f........
......f112225555522211f.......
.....f111225ff555522111f......
....f1111225ff5555221111f.....
....f1111225555555221111f.....
.....f11112255555221111f......
......f111122555221111f.......
.......f1111222221111f........
........f11111111111f.........
.........fffffffffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........fffffffffff..........
........f11222222211f.........
.......f1122222222211f........
......f112225555522211f.......
.....f11122555555522111f......
....f11112255ff555221111f.....
....f11112255ff555221111f.....
.....f11112255555221111f......
......f111122555221111f.......
.......f1111222221111f........
........f11111111111f.........
.........fffffffffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........fffffffffff..........
........f11222222211f.........
.......f1122222222211f........
......f112225555522211f.......
.....f111225555ff522111f......
....f1111225555ff5221111f.....
....f1111225555555221111f.....
.....f11112255555221111f......
......f111122555221111f.......
.......f1111222221111f........
........f11111111111f.........
.........fffffffffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`];
            case "Cup Animation":
            case "anim15":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 5 5 . . 5 . . . 5 . . 5 5 . 
. . 5 9 5 5 9 5 . 5 9 5 5 9 5 . 
. . . 5 9 7 5 8 5 8 5 7 9 5 . . 
. . . . 5 9 7 5 8 5 7 9 5 . . . 
. . . . . 5 9 7 5 7 9 5 . . . . 
. . . . . 5 9 7 5 7 9 5 . . . . 
. . . . . 5 9 7 5 7 9 5 . . . . 
. . . . . . 5 9 7 9 5 . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . 5 5 5 5 5 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 5 5 . . 5 . . . 5 . . 5 5 . 
. . 5 6 5 5 6 5 . 5 6 5 5 6 5 . 
. . . 5 6 9 5 b 5 b 5 9 6 5 . . 
. . . . 5 6 9 5 b 5 9 6 5 . . . 
. . . . . 5 6 9 5 9 6 5 . . . . 
. . . . . 5 6 9 5 9 6 5 . . . . 
. . . . . 5 6 9 5 9 6 5 . . . . 
. . . . . . 5 6 9 6 5 . . . . . 
. . . . . . . 5 6 5 . . . . . . 
. . . . . . . 5 6 5 . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . 5 5 5 5 5 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 5 5 . . 5 . . . 5 . . 5 5 . 
. . 5 9 5 5 6 5 . 5 6 5 5 9 5 . 
. . . 5 9 6 7 b 7 b 7 6 9 5 . . 
. . . . 5 9 6 7 b 7 6 9 5 . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . . 5 9 6 9 5 . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . 5 5 5 5 5 . . . . . 
`];
            case "Right Gun":
            case "anim14":return [img`
....bbbbbb...........
..bbbdddbcb..........
.bbddddbcccb.........
.bdddbbddddb.........
.bbbbddccccdb........
.bdcccbbbbdcb........
bbbbbbb111bb.........
bb144ebf441...cccccc.
b114d41fdd1..cc11111c
.b1114ddd1d..c.dddcc.
..b8114414dd1ccccc...
...8dddd4411.c.......
...8dddd1d8..c.......
...84444558..........
....888888...........
.....888.............
.....................
.....................
.....................
.....................
.....................
`, img`
....bbbbbb...........
..bbbdddbcb..........
.bbddddbcccb.........
.bdddbbddddb.........
.bbbbddccccdb........
.bdcccbbbbdcb........
bbbbbbb111bb.ccccccc.
bb144ebf441.cc11111c.
b114d41fdd1.c.dddccc.
.b1114ddd1d..cccc....
..b8114414dd1.c......
...8dddd4411...c.....
...8dddd1d8..........
...84444558..........
....888888...........
.....888.............
.....................
.....................
.....................
.....................
.....................
`];
            case "Left Gun":
            case "anim13":return [img`
...........bbbbbb....
..........bcbdddbbb..
.........bcccbddddbb.
.........bddddbbdddb.
........bdccccddbbbb.
........bcdbbbbcccdb.
.........bb111bbbbbbb
.cccccc...144fbe441bb
c11111cc..1ddf14d411b
.ccddd.c..d1ddd4111b.
...ccccc1dd4144118b..
.......c.1144dddd8...
.......c..8d1dddd8...
..........85544448...
...........888888....
.............888.....
.....................
.....................
.....................
.....................
.....................
`, img`
..............bbbbbb.
.............bcbdddbb
............bcccbdddd
............bddddbbdd
...........bdccccddbb
...........bcdbbbbccc
....ccccccc.bb111bbbb
....c11111cc.144fbe44
....cccddd.c.1ddf14d4
.......cccc..d1ddd411
.........c.1dd4144118
........c...1144dddd8
.............8d1dddd8
.............85544448
..............888888.
................888..
.....................
.....................
.....................
.....................
.....................
`];
            case "Back Soldier Animation":
            case "anim10":return [img`
......dddd...........
....dd1111dd.........
...d111dd111d........
..ddddd22ddddd.......
..dd12122121dd.......
..d12d2dd2d21d.......
..ddd221122ddd.......
.dd1d2d11d2d1dd......
.d11dd1111d111d......
..d1111111111d.......
...d11111111d........
..e4666666664e.......
..4d6bbbbbb6d4.......
..446444444644.......
.....666666..........
.....66..66..........
.....................
.....................
.....................
.....................
.....................
`, img`
.....................
......dddd...........
....dd1111dd.........
...d111dd111d........
...dddd22dddd........
..dd12122121dd.......
..d12d2ddd2d1d.......
..ddd2d1122ddd.......
..d12dd112d11d.......
.dd1dd111d111dd......
.dd1111111111dd......
...d11111111d........
...16666666641.......
...46bbbbb1dd4.......
...1666666114........
....666..............
.....................
.....................
.....................
.....................
.....................
`, img`
......dddd...........
....dd1111dd.........
...d111dd111d........
..ddddd22ddddd.......
..dd12122121dd.......
..d12d2dd2d21d.......
..ddd221122ddd.......
.dd1d2d11d2d1dd......
.d11dd1111d111d......
..d1111111111d.......
...d11111111d........
..e4666666664e.......
..4d6bbbbbb6d4.......
..446444444644.......
.....666666..........
.....66..66..........
.....................
.....................
.....................
.....................
.....................
`, img`
.....................
......dddd...........
....dd1111dd.........
...d111dd111d........
...dddd22dddd........
..dd12122121dd.......
..d1d2ddd2d21d.......
..ddd2211d2ddd.......
..d11d211dd21d.......
.dd111d111dd1dd......
.dd1111111111dd......
...d11111111d........
..14666666661........
..4dd1bbbbb64........
...4116666661........
.........666.........
.....................
.....................
.....................
.....................
.....................
`];
            case "Soldier Animation":
            case "anim5":return [img`
......dddd...........
....ddd22ddd.........
...ddd2222ddd........
..ddd111111ddd.......
..dd122222211d.......
..d12dddddd21d.......
..dddd1111dddd.......
.dd1dbf44fbd1dd......
.d1141fddf1411d......
..d11dddddd11d.......
...d11444411d........
..146bbbbbb641.......
..4d6bbbbbb6d4.......
..446445544644.......
.....666666..........
.....66..66..........
.....................
.....................
.....................
.....................
.....................
`, img`
.....................
......dddd...........
....ddd22ddd.........
...ddd2222ddd........
..ddd111111ddd.......
..dd122222211d.......
.dd12dddddd21dd......
.ddddd1111ddddd......
..d1dbf44fbd1d.......
..d141fddf141d.......
...614dddd41f1.......
..616cccc1dd41.......
..146cccc1dd1........
....64455611.........
....6666666..........
....666..............
.....................
.....................
.....................
.....................
.....................
`, img`
......dddd...........
....ddd22ddd.........
...ddd2222ddd........
..ddd111111ddd.......
..dd122222211d.......
..d12dddddd21d.......
..dddd1111dddd.......
.dd1dbf44fbd1dd......
.d1141fddf1411d......
..d11dddddd11d.......
...d11444411d........
..146bbbbbb641.......
..4d6bbbbbb6d4.......
..446445544644.......
.....666666..........
.....66..66..........
.....................
.....................
.....................
.....................
.....................
`, img`
.....................
......dddd...........
....ddd22ddd.........
...ddd2222ddd........
..ddd111111ddd.......
..d112222221dd.......
.dd12dddddd21dd......
.ddddd1111ddddd......
..d1dbf44fbd1d.......
..d141fddf141d.......
..1d14dddd416........
..14dd1bbbb616.......
...1dd1bbbb641.......
....11655446.........
.....6666666.........
.........666.........
.....................
.....................
.....................
.....................
.....................
`];
            case "Danh phai":
            case "anim12":return [img`
....bbbbbb...........
..bbbdddbcb..........
.bbddddbcccb.........
.bdddbbddddb...cc....
.bbbbddccccdb.cdc....
.bdcccbbbbdcbcddc....
bbbbbbb111bbcddc.....
bb144ebf441cddc......
b114d41fdd1cdc.......
.b1114ddd1dccc.......
..b8114414dd1........
...8dddd4411.........
...8dddd1d8..........
...84444558..........
....888888...........
.....888.............
.....................
.....................
.....................
.....................
.....................
`, img`
.....................
.......bbb...........
....bbbbbcb..........
..bbdddddccbb........
.bbddddddcccbb.......
.bddddbbbddddb.......
.bbbbbdddccccdb......
bbbdcccbbbbbdcb......
bbbbbbbbb111bbb.....c
b1b1441bbf4411b...ccd
.b114d4bbfdd1b..ccddc
..b1114dddddb11cdddc.
...8ddddddd11ddcdcc..
...8444445144ddccc...
...888888881111......
...888...88..........
.....................
.....................
.....................
.....................
.....................
`, img`
.......bb............
....bbbbcbb..........
..bbddddbcbb.........
.bbdddddbccbb........
.bddddbbddddb........
.bbbbbddccccdb.......
bbbccccbbbbdcb.......
bbbbbbbb111bbb.......
b1b1441bf4411b.......
.b114d4bfdd1b........
..b1114ddd11.c.......
...8dddd11dd1ccccccc.
...8444144dd1cddddd..
...888881111.ccccc...
..88888888...c.......
..888..88............
.....................
.....................
.....................
.....................
.....................
`, img`
....bbbbbb...........
..bbccccbdb..........
.bbccccbdddb.........
.bcccbbccccb.........
.bbbbccddddcb........
.bcdddbbbbcdb........
bbbbbbbcccbbb........
bb1441bf4411b........
b114d41fdd1b.........
.b1114ddddb..........
..bdd14441b..........
..bdd1ddccc..........
...11bddcdc..........
...84444cddc.........
....88888cddc........
.....888..cddc.......
...........cdc.......
............cc.......
.....................
.....................
.....................
`];
            case "Danh trai":
            case "anim11":return [img`
.......bbbbbb........
......bcbdddbbb......
.....bcccbddddbb.....
cc...bddddbbdddb.....
cdc.bdccccddbbbb.....
cddcbcdbbbbcccdb.....
.cddcbb111bbbbbbb....
..cddc144fbe441bb....
...cdc1ddf14d411b....
...cccd1ddd4111b.....
....1dd4144118b......
.....1144dddd8.......
......8d1dddd8.......
......85544448.......
.......888888........
.........888.........
.....................
.....................
.....................
.....................
.....................
`, img`
.....................
..............bbb....
.............bcbbbbb.
...........bbccdddddb
..........bbcccdddddd
..........bddddbbbddd
.........bdccccdddbbb
.........bcdbbbbbcccd
..cc.....bbb111bbbbbb
..cdcc...b1144fbb1441
..ccddcc..b1ddfbb4d41
....cdddc11bddddd4111
.....ccdcdd11ddddddd8
......cccdd4415444448
.........111188888888
.............88...888
.....................
.....................
.....................
.....................
.....................
`, img`
..............bbbbbb.
.............bbcbbbbb
............bbcbddddb
.......cc..bbccbddddd
.......cdc.bddddbbddd
.......cddbdccccddbbb
........cdbcdbbbbcccc
.........cbbb111bbbbb
..........b1144fb1441
..........cb1ddfb4d41
..........c111ddd4111
....ccccccc1dd11dddd8
.....dddddc1dd4414448
......ccccc.111188888
..........c...8888888
...............888888
.....................
.....................
.....................
.....................
.....................
`, img`
..............bbbbbb.
.............bdbccccb
............bdddbcccc
............bccccbbcc
...........bcddddccbb
...........bdcbbbbddd
...........bbbcccbbbb
...........b1144fb144
............b1ddf14d4
.............bdddd411
.............b14441dd
.............cccdd1dd
.............cdcddb11
............cddc44448
...........cddc88888.
..........cddc..888..
..........cdc........
..........cc.........
.....................
.....................
.....................
`];
            case "C_animation":
            case "anim3":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . d d d d . . . . . 
. . . . . . d b b b b d . . . . 
. . . . . d b d c c c d . . . . 
. . . . . d b c . . . . . . . . 
. . . . . d b c . . . . . . . . 
. . . . . d b c . . . . . . . . 
. . . . . d b c . . . . . . . . 
. . . . . d b d c c c d . . . . 
. . . . . . d b b b b d . . . . 
. . . . . . . d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . 4 4 4 4 . . . 
. . . . . . . . 4 6 6 6 6 4 . . 
. . . . . . . 4 6 4 c c c 4 . . 
. . . . . . . 4 6 c . . . . . . 
. . . . . . . 4 6 c . . . . . . 
. . . . . . . 4 6 c . . . . . . 
. . . . . . . 4 6 c . . . . . . 
. . . . . . . 4 6 4 c c c 4 . . 
. . . . . . . . 4 6 6 6 6 4 . . 
. . . . . . . . . 4 4 4 4 . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . e e e e . . . . . 
. . . . . . e 6 6 6 6 e . . . . 
. . . . . e 6 e c c c e . . . . 
. . . . . e 6 c . . . . . . . . 
. . . . . e 6 c . . . . . . . . 
. . . . . e 6 c . . . . . . . . 
. . . . . e 6 c . . . . . . . . 
. . . . . e 6 e c c c e . . . . 
. . . . . . e 6 6 6 6 e . . . . 
. . . . . . . e e e e . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . f 6 6 6 6 f . . . . . . 
. . . f 6 f c c c f . . . . . . 
. . . f 6 c . . . . . . . . . . 
. . . f 6 c . . . . . . . . . . 
. . . f 6 c . . . . . . . . . . 
. . . f 6 c . . . . . . . . . . 
. . . f 6 f c c c f . . . . . . 
. . . . f 6 6 6 6 f . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "O_animation":
            case "anim17":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . d d d d . . . . . . 
. . . . . d b b b b d . . . . . 
. . . . d b c 6 6 c b d . . . . 
. . . . d b 6 . . 6 b d . . . . 
. . . . d b 6 . . 6 b d . . . . 
. . . . d b 6 . . 6 b d . . . . 
. . . . d b 6 . . 6 b d . . . . 
. . . . d b c 6 6 c b d . . . . 
. . . . . d b b b b d . . . . . 
. . . . . . d d d d . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . 4 4 4 4 . . . . 
. . . . . . . 4 6 6 6 6 4 . . . 
. . . . . . 4 6 c b b c 6 4 . . 
. . . . . . 4 6 b . . b 6 4 . . 
. . . . . . 4 6 b . . b 6 4 . . 
. . . . . . 4 6 b . . b 6 4 . . 
. . . . . . 4 6 b . . b 6 4 . . 
. . . . . . 4 6 c b b c 6 4 . . 
. . . . . . . 4 6 6 6 6 4 . . . 
. . . . . . . . 4 4 4 4 . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . 6 6 6 6 . . . . . . 
. . . . . 6 b b b b 6 . . . . . 
. . . . 6 b c 7 7 c b 6 . . . . 
. . . . 6 b 7 . . 7 b 6 . . . . 
. . . . 6 b 7 . . 7 b 6 . . . . 
. . . . 6 b 7 . . 7 b 6 . . . . 
. . . . 6 b 7 . . 7 b 6 . . . . 
. . . . 6 b c 7 7 c b 6 . . . . 
. . . . . 6 b b b b 6 . . . . . 
. . . . . . 6 6 6 6 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . f f f f . . . . . . . . 
. . . f b b b b f . . . . . . . 
. . f b c 6 6 c b f . . . . . . 
. . f b 6 . . 6 b f . . . . . . 
. . f b 6 . . 6 b f . . . . . . 
. . f b 6 . . 6 b f . . . . . . 
. . f b 6 . . 6 b f . . . . . . 
. . f b c 6 6 c b f . . . . . . 
. . . f b b b b f . . . . . . . 
. . . . f f f f . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "I_animation":
            case "anim2":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . d d d d d d d . . . . 
. . . . . d b 6 6 6 b d . . . . 
. . . . . . d b 6 b d . . . . . 
. . . . . . . b 6 b . . . . . . 
. . . . . . . d 6 d . . . . . . 
. . . . . . . d 6 d . . . . . . 
. . . . . . . d 6 d . . . . . . 
. . . . . . . b 6 b . . . . . . 
. . . . . . d b 6 b d . . . . . 
. . . . . d b 6 6 6 b d . . . . 
. . . . . d d d d d d d . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . 4 4 4 4 4 4 4 . . . 
. . . . . . 4 e b b b e 4 . . . 
. . . . . . . 4 e b e 4 . . . . 
. . . . . . . . e b e . . . . . 
. . . . . . . . 4 b 4 . . . . . 
. . . . . . . . 4 b 4 . . . . . 
. . . . . . . . 4 b 4 . . . . . 
. . . . . . . . e b e . . . . . 
. . . . . . . 4 e b e 4 . . . . 
. . . . . . 4 e b b b e 4 . . . 
. . . . . . 4 4 4 4 4 4 4 . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 6 6 6 6 6 6 6 . . . . . 
. . . . 6 c b b b c 6 . . . . . 
. . . . . 6 c b c 6 . . . . . . 
. . . . . . c b c . . . . . . . 
. . . . . . 6 b 6 . . . . . . . 
. . . . . . 6 b 6 . . . . . . . 
. . . . . . 6 b 6 . . . . . . . 
. . . . . . c b c . . . . . . . 
. . . . . 6 c b c 6 . . . . . . 
. . . . 6 c b b b c 6 . . . . . 
. . . . 6 6 6 6 6 6 6 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . f f f f f f f . . . . . . 
. . . f c b b b c f . . . . . . 
. . . . f c b c f . . . . . . . 
. . . . . f b f . . . . . . . . 
. . . . . f b f . . . . . . . . 
. . . . . f b f . . . . . . . . 
. . . . . f b f . . . . . . . . 
. . . . . f b f . . . . . . . . 
. . . . f c b c f . . . . . . . 
. . . f c b b b c f . . . . . . 
. . . f f f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "R_animation":
            case "anim18":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . d d d . . . . . . . 
. . . . . d b b b d . . . . . . 
. . . . . d b . . b d . . . . . 
. . . . . d b . . . b d . . . . 
. . . . . d b . . . b d . . . . 
. . . . . d b . b d d . . . . . 
. . . . . d b b d . . . . . . . 
. . . . . d b . b d . . . . . . 
. . . . . d b . . b d . . . . . 
. . . . . d b . . . b d . . . . 
. . . . . d d . . . . b d . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . 4 4 4 . . . . . 
. . . . . . . 4 c b b 4 . . . . 
. . . . . . . 4 b . . b 4 . . . 
. . . . . . . 4 b . . . b 4 . . 
. . . . . . . 4 b . . . b 4 . . 
. . . . . . . 4 b . b 4 4 . . . 
. . . . . . . 4 b b 4 . . . . . 
. . . . . . . 4 b . b 4 . . . . 
. . . . . . . 4 b . . b 4 . . . 
. . . . . . . 4 b . . . b 4 . . 
. . . . . . . 4 4 . . . . b 4 . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . e e e . . . . . . . 
. . . . . e d d d e . . . . . . 
. . . . . e d . . d e . . . . . 
. . . . . e d . . . d e . . . . 
. . . . . e d . . . d e . . . . 
. . . . . e d . d e e . . . . . 
. . . . . e d d e . . . . . . . 
. . . . . e d . d e . . . . . . 
. . . . . e d . . d e . . . . . 
. . . . . e d . . . d e . . . . 
. . . . . e e . . . . d e . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . f f f . . . . . . . . . . 
. . f c c c f . . . . . . . . . 
. . f c . . c f . . . . . . . . 
. . f c . . . c f . . . . . . . 
. . f c . . . c f . . . . . . . 
. . f c . c f f . . . . . . . . 
. . f c c f . . . . . . . . . . 
. . f c . c f . . . . . . . . . 
. . f c . . c f . . . . . . . . 
. . f c . . . c f . . . . . . . 
. . f f . . . . c f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "V_animation":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . d d d . . . d d d . . . 
. . . . d 6 b . . . b 6 d . . . 
. . . . d 6 b . . . b 6 d . . . 
. . . . d 6 b . . . b 6 d . . . 
. . . . . d 6 b . b 6 d . . . . 
. . . . . d 6 b . b 6 d . . . . 
. . . . . . d 6 b 6 d . . . . . 
. . . . . . . d 6 d . . . . . . 
. . . . . . . . d . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 5 5 . . . 5 5 . . 
. . . . . . . 5 9 . . . b 5 . . 
. . . . . . . 5 9 . . . b 5 . . 
. . . . . . . 5 9 . . . b 5 . . 
. . . . . . . . 5 b . 9 5 . . . 
. . . . . . . . 5 b . 9 5 . . . 
. . . . . . . . . 5 b 5 . . . . 
. . . . . . . . . 5 9 5 . . . . 
. . . . . . . . . . 5 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 . . . 1 1 . . . . 
. . . . . 1 6 . . . 6 1 . . . . 
. . . . . 1 6 . . . 6 1 . . . . 
. . . . . 1 6 . . . 6 1 . . . . 
. . . . . . 1 6 . 6 1 . . . . . 
. . . . . . 1 6 . 6 1 . . . . . 
. . . . . . . 1 6 1 . . . . . . 
. . . . . . . 1 6 1 . . . . . . 
. . . . . . . . 1 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . f f . . . f f . . . . . . . 
. . f 9 . . . 9 f . . . . . . . 
. . f 9 . . . 9 f . . . . . . . 
. . f 9 . . . 9 f . . . . . . . 
. . . f 9 . 9 f . . . . . . . . 
. . . f 9 . 9 f . . . . . . . . 
. . . . f 9 f . . . . . . . . . 
. . . . f 9 f . . . . . . . . . 
. . . . . f . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "T_animation":
            case "anim4":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . d d d d d d d d d . . . 
. . . . d b b c c c b b d . . . 
. . . . . d b b c b b d . . . . 
. . . . . . . d c d . . . . . . 
. . . . . . . d c d . . . . . . 
. . . . . . . d c d . . . . . . 
. . . . . . . d c d . . . . . . 
. . . . . . . d b d . . . . . . 
. . . . . . . d b d . . . . . . 
. . . . . . . d d d . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . 4 4 4 4 4 4 4 4 4 . 
. . . . . . 4 d d b b b d d 4 . 
. . . . . . . 4 d d b d d 4 . . 
. . . . . . . . . 4 b 4 . . . . 
. . . . . . . . . 4 b 4 . . . . 
. . . . . . . . . 4 b 4 . . . . 
. . . . . . . . . 4 b 4 . . . . 
. . . . . . . . . 4 d 4 . . . . 
. . . . . . . . . 4 d 4 . . . . 
. . . . . . . . . 4 4 4 . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . e e e e e e e e e . . . 
. . . . e 6 6 c c c 6 6 e . . . 
. . . . . e 6 6 c 6 6 e . . . . 
. . . . . . . e c e . . . . . . 
. . . . . . . e c e . . . . . . 
. . . . . . . e c e . . . . . . 
. . . . . . . e c e . . . . . . 
. . . . . . . e 6 e . . . . . . 
. . . . . . . e 6 e . . . . . . 
. . . . . . . e e e . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . f f f f f f f f f . . . . . 
. . f a a c c c a a f . . . . . 
. . . f a a c a a f . . . . . . 
. . . . . f c f . . . . . . . . 
. . . . . f c f . . . . . . . . 
. . . . . f c f . . . . . . . . 
. . . . . f c f . . . . . . . . 
. . . . . f a f . . . . . . . . 
. . . . . f a f . . . . . . . . 
. . . . . f f f . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
