// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image5":
            case "Seed":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . c c . . . . . . . 
. . . . . . c 4 4 c . . . . . . 
. . . . . . c 4 4 c . . . . . . 
. . . . . . . c c . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "The eye":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........fffffffffff..........
........f11222222211f.........
.......f1122222222211f........
......f112225555522211f.......
.....f111225ff555522111f......
....f1111225ff5555221111f.....
....f1111225555555221111f.....
.....f11112255555221111f......
......f111122555221111f.......
.......f1111222221111f........
........f11111111111f.........
.........fffffffffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
            case "image1":
            case "soldier":return img`
. . . . . . d d d d . . . . . . 
. . . . d d d 2 2 d d d . . . . 
. . . d d d 2 2 2 2 d d d . . . 
. . d d d 1 1 1 1 1 1 d d d . . 
. . d d 1 2 2 2 2 2 2 1 1 d . . 
. . d 1 2 d d d d d d 2 1 d . . 
. . d d d d 1 1 1 1 d d d d . . 
. d d 1 d b f 4 4 f b d 1 d d . 
. d 1 1 4 1 f d d f 1 4 1 1 d . 
. . d 1 1 d d d d d d 1 1 d . . 
. . . d 1 1 4 4 4 4 1 1 d . . . 
. . 1 4 6 b b b b b b 6 4 1 . . 
. . 4 d 6 b b b b b b 6 d 4 . . 
. . 4 4 6 4 4 5 5 4 4 6 4 4 . . 
. . . . . 6 6 6 6 6 6 . . . . . 
. . . . . 6 6 . . 6 6 . . . . . 
`;
            case "image2":
            case "Cup":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 5 5 . . 5 . . . 5 . . 5 5 . 
. . 5 9 5 5 6 5 . 5 6 5 5 9 5 . 
. . . 5 9 6 7 b 7 b 7 6 9 5 . . 
. . . . 5 9 6 7 b 7 6 9 5 . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . . 5 9 6 9 5 . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . 5 5 5 5 5 . . . . . 
`;
            case "image3":
            case "myImage":return img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c b b b b b b c b b c c c . . 
. c 1 b b b 1 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b c b b b c b b b b f . . . . 
f b 1 f f f 1 b b b b f c . . . 
f b b b b b b b b b b f c c . . 
. f b b b b b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`;
            case "image4":
            case "Power":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . 4 . . . . . . . 
. . . . . . 3 3 4 4 4 . . . . . 
. . . . . 4 3 3 2 1 1 4 . . . . 
. . . . 4 3 3 3 2 2 5 4 4 . . . 
. . . . 4 4 3 2 4 4 4 4 4 . . . 
. . . . 4 2 3 2 4 4 4 4 4 . . . 
. . . . . 4 2 3 4 4 2 4 . . . . 
. . . . . . 2 2 2 2 2 . . . . . 
. . . . . . . . 4 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image7":
            case "bat":return img`
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . a a . . . . 
. . . a 5 5 a . . . 
. . . a 5 5 a . . . 
. . . . a a . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
`;
            case "image8":
            case "V":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. f f f f f . . . . . f f f f . 
. . f 1 1 f . . . . f f 1 1 1 f 
. . f 1 1 f . . . . f 1 1 1 1 f 
. . f 1 1 f f . . f f 1 1 1 1 f 
. . f 1 1 1 f . . f 1 1 1 1 1 f 
. . . f 1 1 1 f f f 1 1 1 1 1 f 
. . . f 1 1 1 f f 1 1 1 1 1 f . 
. . . . f 1 1 1 f 1 1 1 1 1 f . 
. . . . f f 1 1 1 1 1 1 1 f . . 
. . . . . f 1 1 1 1 1 1 f f . . 
. . . . . f f 1 1 1 f f f . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . . f . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image9":
            case "I":return img`
. . . . . f f f f f f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 f f . . . . . 
. . . . . . f 1 1 f f . . . . . 
. . . . . . f 1 f f f . . . . . 
. . . . . . f f f f f . . . . . 
`;
            case "image10":
            case "C":return img`
. . . . f f f f f f f f f . . . 
. . . f f 1 1 1 1 1 1 1 f f . . 
. . . f 1 1 1 1 1 1 1 1 1 f . . 
. . . f 1 1 1 1 1 1 1 1 f f . . 
. . . f 1 1 1 1 1 f f f f . . . 
. . . f 1 1 1 f f f . . . . . . 
. . . f 1 1 f f . . . . . . . . 
. . . f 1 1 f f . . . . . . . . 
. . . f 1 1 1 f . . . . . . . . 
. . . f 1 1 1 f . . . . . . . . 
. . . f 1 1 1 f f . . . . . . . 
. . . f 1 1 1 1 f f f . . . . . 
. . . f 1 1 1 1 1 1 f f f . . . 
. . . f f 1 1 1 1 1 1 1 f f . . 
. . . . f f 1 1 1 1 1 1 1 f . . 
. . . . . f f f f f f f f f . . 
`;
            case "image11":
            case "T":return img`
. . f f f f f f f f f f f . . . 
. . f 1 1 1 1 1 1 f f 1 f . . . 
. . f 1 1 1 1 1 1 1 1 1 f f . . 
. f 1 1 1 1 1 1 1 1 1 1 1 f . . 
. f f f f f f 1 1 f f 1 1 f . . 
. . . . . . . f 1 1 f f f f . . 
. . . . . . . f 1 1 f . . . . . 
. . . . . . f f 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 1 f . . . . . 
. . . . . . f 1 1 f . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image12":
            case "O":return img`
. . . . . f f f f f f f f . . . 
. . . . f f 1 1 1 1 1 1 f . . . 
. . . f f 1 1 1 1 1 1 1 1 f . . 
. . f f 1 1 1 1 1 1 1 1 1 f . . 
. . f 1 1 1 1 1 f f f 1 1 f . . 
. f 1 1 1 1 1 f f . f 1 1 1 f . 
. f 1 1 1 1 f f . . f 1 1 1 f . 
f f 1 1 1 1 f . . . f 1 1 1 f . 
f 1 1 1 1 1 f . . . f 1 1 1 f . 
f 1 1 1 1 1 f f f f f 1 1 1 f . 
f 1 1 1 1 1 1 1 1 1 1 1 1 1 f . 
. f 1 1 1 1 1 1 1 1 1 1 1 f . . 
. f f 1 1 1 1 1 1 1 1 1 1 f . . 
. . f f f 1 1 1 1 1 1 1 f f . . 
. . . . . f f f f f f f . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":
            case "R":return img`
. . . f f f f . . . . . . . . . 
. . . f 1 1 f f f f f . . . . . 
. . . f 1 1 1 1 1 1 f . . . . . 
. . . f 1 f f 1 1 1 f f . . . . 
. . f f 1 f f 1 f f f f . . . . 
. . f 1 1 1 1 1 f . . . . . . . 
. . f 1 1 f 1 1 1 f . . . . . . 
. f f 1 f f f 1 1 f . . . . . . 
. f 1 1 f . f f 1 f . . . . . . 
. f 1 f . . . f 1 1 f . . . . . 
. f 1 f . . . f 1 1 f f . . . . 
. f f f . . . f 1 1 1 f f . . . 
. f f f . . . f 1 1 1 1 f . . . 
. . . . . . . f f f f f f . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "BL":
            case "anim1":return [img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c b b b b b b c b b c c c . . 
. c 2 b b b 2 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b c b b b c b b b b f . . . . 
f b 1 f f f 1 b b b b f c . . . 
f b b 2 b b b 2 b b b f c c . . 
. f b b b b b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`, img`
. . f f f . . . . . . . . . . . 
f f f c c . . . . . . . . f f f 
f f c c . . c c . . . f c b b c 
f f c 3 c c 3 c c f f b b b c . 
f f b 3 b c 3 b c f b b c c c . 
. c b b b b b b c f b c b c c . 
. c b b b b b b c b b c b b c . 
c b 2 b b b 2 b b b c c c b c . 
c b b b b b b b b c c c c c . . 
f b c b b b c b b b b f c . . . 
f b 1 f f f 1 b b b b f c c . . 
. f b 2 b b b b 2 b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . c c . . c c . . . . . . . . 
. . c 3 c c 3 c c c . . . . . . 
. c b 3 b c 3 b c c c . . . . . 
. c b b b b b b b b f f . . . . 
c c b b b b b b b b f f . . . . 
c b 2 b b b 2 b b c f f f . . . 
c b b b b b b b b f f f f . . . 
f b c b b b c b c c b b b . . . 
f b 1 f f f 1 b f c c c c . . . 
. f b 2 b b b 2 f b b c c . . . 
c c f b b b b b c c b b c . . . 
c c c f f f f f f c c b b c . . 
. c c c . . . . . . c c c c c . 
. . c c c . . . . . . . c c c c 
. . . . . . . . . . . . . . . . 
`, img`
. f f f . . . . . . . . f f f . 
f f c . . . . . . . f c b b c . 
f c c . . . . . . f c b b c . . 
c f . . . . . . . f b c c c . . 
c f f . . . . . f f b b c c . . 
f f f c c . c c f b c b b c . . 
f f f c c c c c f b c c b c . . 
. f c 3 c c 3 b c b c c c . . . 
. c b 3 b c 3 b b c c c c . . . 
c c b b b b b b b b c c . . . . 
c b 2 b b b 2 b b b b f c . . . 
f b b b b b b b b b b f c c . . 
f b c b b b c b b b b f . . . . 
. f 1 f f f 1 b b b c f . . . . 
. . f 2 b b b 2 b c f . . . . . 
. . . f f f f f f f . . . . . . 
`];
            case "BR":
            case "anim2":return [img`
f f f . . . . . . . . f f f . . 
c b b c f . . . . . . c c f f . 
. c b b c f . . . . . . c c f f 
. c c c b f . . . . . . c f c f 
. c c b b c f . c c . c c f f f 
. c b b c b f c c 3 c c 3 c f f 
. c b c c b f c b 3 c b 3 b f f 
. . c c c b b c b b b b b b c . 
. . . c c c c b b 2 b b b 2 c . 
. . . . c c b b b b b b b b b c 
. . . . f b b b b c b b b c b c 
. . . c f b b b b 1 f f f 1 b f 
. . c c f b b b 2 b b b 2 b b f 
. . . . f c b b b b b b b b f . 
. . . . . f c b b b b b b f . . 
. . . . . . f f f f f f f . . . 
`, img`
. . . . . . . . . . . f f f . . 
f f f . . . . . . . . c c f f f 
c b b c f . . . c c . . c c f f 
. c b b b f f c c 3 c c 3 c f f 
. c c c b b f c b 3 c b 3 b f f 
. c c b c b f c b b b b b b c . 
. c b b c b b c b b b b b b c . 
. c b c c c b b b 2 b b b 2 b c 
. . c c c c c b b b b b b b b c 
. . . c f b b b b c b b b c b f 
. . c c f b b b b 1 f f f 1 b f 
. . . . f c b b 2 b b b 2 b f . 
. . . . . f c b b b b b b f . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . c c . . c c . . 
. . . . . . c c c 3 c c 3 c . . 
. . . . . c c c b 3 c b 3 b c . 
. . . . f f b b b b b b b b c . 
. . . . f f b b b b b b b b c c 
. . . f f f c b b 2 b b b 2 b c 
. . . f f f f b b b b b b b b c 
. . . b b b c c b c b b b c b f 
. . . c c c c f b 1 f f f 1 b f 
. . . c c b b f 2 b b b 2 b f . 
. . . c b b c c b b b b b f c c 
. . c b b c c f f f f f f c c c 
. c c c c c . . . . . . c c c . 
c c c c . . . . . . . c c c . . 
. . . . . . . . . . . . . . . . 
`, img`
. f f f . . . . . . . . f f f . 
. c b b c f . . . . . . . c f f 
. . c b b c f . . . . . . c c f 
. . c c c b f . . . . . . . f c 
. . c c b b f f . . . . . f f c 
. . c b b c b f c c . c c f f f 
. . c b c c b f c c c c c f f f 
. . . c c c b c b 3 c c 3 c f . 
. . . c c c c b b 3 c b 3 b c . 
. . . . c c b b b b b b b b c c 
. . . c f b b b b 2 b b b 2 b c 
. . c c f b b b b b b b b b b f 
. . . . f b b b b c b b b c b f 
. . . . f c b b b 1 f f f 1 f . 
. . . . . f c b 2 b b b 2 f . . 
. . . . . . f f f f f f f . . . 
`];
            case "BAL":
            case "anim3":return [img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c 2 b b b 2 b c b b c c c . . 
. c 2 b b b 2 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b 1 f f 1 c b b b b f . . . . 
f f 1 f f 1 f 2 b b b f c . . . 
f f 2 2 2 2 f b b b b f c c . . 
. f 2 2 2 2 b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`, img`
. . f f f . . . . . . . . . . . 
f f f c c . . . . . . . . f f f 
f f c c c . c c . . . f c b b c 
f f c 3 c c 3 c c f f b b b c . 
f f c 3 b c 3 b c f b b c c c . 
f c b b b b b b c f b c b c c . 
c c 2 b b b 2 b c b b c b b c . 
c b b b b b b b b b c c c b c . 
c b 1 f f 1 c b b c c c c c . . 
c f 1 f f 1 f 2 b b b f c . . . 
f f f f f f f b b b b f c . . . 
f f 2 2 2 2 f b b b b f c c . . 
. f 2 2 2 2 2 b b b c f . . . . 
. . f 2 2 2 b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . c c . c c . . . . . . . . 
. . f 3 c c 3 c c c . . . . . . 
. f c 3 b c 3 b c c c . . . . . 
f c b b b b b b b b f f . . . . 
c c 2 b b b 2 b b b f f . . . . 
c b b b b b b b b c f f f . . . 
c b 1 f f 1 c b b f f f f . . . 
f f 1 f f 1 f 2 c c b b b . . . 
f f f f f f f b f c c c c . . . 
f f 2 2 2 2 f b f b b c c c . . 
. f 2 2 2 2 2 b c c b b c . . . 
. . f 2 2 2 b f f c c b b c . . 
. . . f f f f f f f c c c c c . 
. . . . . . . . . . . . c c c c 
`, img`
. f f f . . . . . . . . f f f . 
f f c . . . . . . . f c b b c . 
f c c . . . . . . f c b b c . . 
c f . . . . . . . f b c c c . . 
c f f . . . . . f f b b c c . . 
f f f c c . c c f b c b b c . . 
f f f c c c c c f b c c b c . . 
. f c 3 c c 3 b c b c c c . . . 
. c b 3 b c 3 b b c c c c . . . 
c c b b b b b b b b c c . . . . 
c 2 2 b b b 2 2 b b b f c . . . 
f b b b b b b b b b b f c c . . 
f b c b b b c b b b b f . . . . 
. f 1 f f f 1 b b b c f . . . . 
. . f 2 b b b 2 b c f . . . . . 
. . . f f f f f f f . . . . . . 
`];
            case "BAR":
            case "anim4":return [img`
f f f . . . . . . . . f f f . . 
c b b c f . . . . . . c c f f . 
. c b b c f . . . . . . c c f f 
. c c c b f . . . . . . c f c f 
. c c b b c f . c c . c c f f f 
. c b b c b f c c 3 c c 3 c f f 
. c b c c b f c b 3 c b 3 b f f 
. . c c c b b c b 2 b b b 2 c . 
. . . c c c c b b 2 b b b 2 c . 
. . . . c c b b b b b b b b b c 
. . . . f b b b b c 1 f f 1 b c 
. . . c f b b b 2 f 1 f f 1 f f 
. . c c f b b b b f 2 2 2 2 f f 
. . . . f c b b b b 2 2 2 2 f . 
. . . . . f c b b b b b b f . . 
. . . . . . f f f f f f f . . . 
`, img`
. . . . . . . . . . . f f f . . 
f f f . . . . . . . . c c f f f 
c b b c f . . . c c . c c c f f 
. c b b b f f c c 3 c c 3 c f f 
. c c c b b f c b 3 c b 3 c f f 
. c c b c b f c b b b b b b c f 
. c b b c b b c b 2 b b b 2 c c 
. c b c c c b b b b b b b b b c 
. . c c c c c b b c 1 f f 1 b c 
. . . c f b b b 2 f 1 f f 1 f c 
. . . c f b b b b f f f f f f f 
. . c c f b b b b f 2 2 2 2 f f 
. . . . f c b b b 2 2 2 2 2 f . 
. . . . . f c b b b 2 2 2 f . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . c c . c c . . . 
. . . . . . c c c 3 c c 3 f . . 
. . . . . c c c b 3 c b 3 c f . 
. . . . f f b b b b b b b b c f 
. . . . f f b b b 2 b b b 2 c c 
. . . f f f c b b b b b b b b c 
. . . f f f f b b c 1 f f 1 b c 
. . . b b b c c 2 f 1 f f 1 f f 
. . . c c c c f b f f f f f f f 
. . c c c b b f b f 2 2 2 2 f f 
. . . c b b c c b 2 2 2 2 2 f . 
. . c b b c c f f b 2 2 2 f . . 
. c c c c c f f f f f f f . . . 
c c c c . . . . . . . . . . . . 
`, img`
. f f f . . . . . . . . f f f . 
. c b b c f . . . . . . . c f f 
. . c b b c f . . . . . . c c f 
. . c c c b f . . . . . . . f c 
. . c c b b f f . . . . . f f c 
. . c b b c b f c c . c c f f f 
. . c b c c b f c c c c c f f f 
. . . c c c b c b 3 c c 3 c f . 
. . . c c c c b b 3 c b 3 b c . 
. . . . c c b b b b b b b b c c 
. . . c f b b b 2 2 b b b 2 2 c 
. . c c f b b b b b b b b b b f 
. . . . f b b b b c b b b c b f 
. . . . f c b b b 1 f f f 1 f . 
. . . . . f c b 2 b b b 2 f . . 
. . . . . . f f f f f f f . . . 
`];
            case "SL":
            case "anim6":return [img`
.............ccfff..............
...........ccddbcf..............
..........ccddbbf...............
..........fccbbcf...............
.....fffffccccccff.........ccc..
...ffbbbbbbbcbbbbcfff....ccbbc..
..fbbbbbbbbcbcbbbbcccff.cdbbc...
ffbbbbbbffbbcbcbbbcccccfcdbbf...
fbcbbb112f1bcbbbbbcccccffbbf....
fbbb11111111bbbbbcccccccbbcf....
.fb11133cc11bbbbcccccccccccf....
..fccc31c211bbbcccccbdbffbbcf...
...fc13c111cbbbfcddddcc..fbbf...
....fccc111fbdbbccdcc.....fbbf..
........ccccfcdbbcc........fff..
.............fffff..............
`, img`
.............ccfff..............
............cddbbf..............
...........cddbbf...............
..........fccbbcf............ccc
....ffffffccccccff.........ccbbc
..ffbbbbbbbbbbbbbcfff.....cdbbc.
ffbbbbbbbbbcbcbbbbcccff..cddbbf.
fbcbbbbbffbbcbcbbbcccccfffdbbf..
fbbb11112f1bcbcbbbcccccccbbbcf..
.fb11111111bbbbbbcccccccccbccf..
..fccc33cc11bbbbccccccccfffbbcf.
...fc131c211bbbcccccbdbc...fbbf.
....f33c111cbbbfdddddcc.....fbbf
.....ff1111fbdbbfddcc........fff
.......cccccfbdbbfc.............
.............fffff..............
`, img`
..............cfff..............
............ccddbf..............
...........cbddbff.........ccc..
..........fccbbcf.........cbbc..
...fffffffccccccff.......cdbc...
.ffcbbbbbbbbbbbbbcfff....cdbf...
fcbbbbbbbbbcbbbbbbcccff.cdbf....
fbcbbbbffbbbcbcbbbcccccffdcf....
fbb11112fbbbcbcbbbccccccbbcf....
.fb11111111bbcbbbccccccccbbcf...
..fccc33cb11bbbbcccccccfffbbf...
...fc131c111bbbcccccbdbc..fbbf..
....f33c211cbbccdddddbc....fff..
.....ff1111fdbbccddbcc..........
.......cccccfdbbbfcc............
.............fffff..............
`, img`
.............ccfff..............
............cddbbf..............
...........cddbbf...............
..........fccbbcf............ccc
....ffffffccccccff.........ccbbc
..ffbbbbbbbbbbbbbcfff.....cdbbc.
ffbbbbbbbbbcbcbbbbcccff..cddbbf.
fbcbbbbbffbbcbcbbbcccccfffdbbf..
fbbb11112f1bcbcbbbcccccccbbbcf..
.fb11111111bbbbbbcccccccccbccf..
..fccc33cc11bbbbccccccccfffbbcf.
...fc131c111bbbcccccbdbc...fbbf.
....f33c211cbbbfdddddcc.....fbbf
.....ff1111fbdbbfddcc........fff
.......cccccfbdbbfc.............
.............fffff..............
`];
            case "SAL":
            case "anim8":return [img`
.................ccfff..............
................cddbbf..............
...............cddbbf...............
..............fccbbcf............ccc
........ffffffccccccff.........ccbbc
......ffbbbbbbbbbbbbbcfff.....cdbbc.
....ffbbbbbbbbbcbcbbbbcccff..cddbbf.
....fbcbbbbbffbbcbcbbbcccccfffdbbf..
....fbbb11112f1bcbcbbbcccccccbbbcf..
.....fb11111111bbbbbbcccccccccbccf..
......fccc33cc11bbbbccccccccfffbbcf.
.......fc131c211bbbcccccbdbc...fbbf.
........f33c111cbbbfdddddcc.....fbbf
.........ff1111fbdbbfddcc........fff
...........cccccfbdbbfc.............
.................fffff..............
`, img`
.................ccfff..............
................cddbbf..............
...............cddbbf...............
.........ffffffccbbcf...............
......fffbbbbbbbbcccff..............
.....fbbbbbbbbbbbbbbbcfff......ccccc
.....bcbbbbbffbcbcbbbbcccff...cdbbbc
.....bbb11112fbbcbcbbbcccccffcddbbc.
.....fb11111111bcbcbbbcccccccbdbbf..
......fccc33c11bbbbbbcccccccccbbcf..
.......fc131cc11bbbbccccccccffbccf..
........f33c2111bbbcccccbdbc..fbbcf.
.........ff1111cbbbfdddddcc....fbbf.
...........ccc1fbdbbfddcc.......fbbf
..............ccfbdbbfc..........fff
.................fffff..............
`, img`
..................ccfff.............
.................cddbbf.............
........fffffffffddbbf..............
.......fbbbbbbbbbfcbcf..............
.......fbbc111bffbbccffff...........
.......fb1111112fbbbbbcccff....ccccc
........f1cc3311bbcbcbbccccf..cdbbbc
........fcc131c1bbbcbcbcccccfcddbbc.
.........f111121bbbcbcbccccccbdbbf..
.........f1111111bbbbbccccccccbbcf..
..........f111111bbbbcccccccffbccf..
...........c1111cbbbcccccbdbc.fbbcf.
............cc11cbbbfddddddc...fbbf.
..............cffbdbbfdddcc.....fbbf
.................fbdbbfcc........fff
..................fffff.............
`, img`
....................ccfff...........
..........fffffffffcbbbbf...........
.........fbbbbbbbbbfffbf............
.........fbb111bffbbbbff............
.........fb111112fbbbbbcff..........
.........f1cccc11bbcbcbcccf.........
..........fc1c1c1bbbcbcbcccf...ccccc
............c3331bbbcbcbccccfccddbbc
...........c333c1bbbbbbbcccccbddbcc.
...........c331c11bbbbbcccccccbbcc..
..........cc13c211bbbbccccccffbccf..
..........c111111cbbbcccccbbc.fccf..
...........cc1111cbbbfdddddc..fbbcf.
.............cccffbdbbfdddc....fbbf.
..................fbdbbfcc......fbbf
...................fffff.........fff
`, img`
...........fffffff...ccfff..........
..........fbbbbbbbffcbbbbf..........
..........fbb111bbbbbffbf...........
..........fb11111ffbbbbff...........
..........f1cccc12fbbbbbcff.........
..........ffc1c1c1bbcbcbcccf........
...........fcc3331bbbcbcbcccf..ccccc
............c333c1bbbcbcbccccfcddbbc
............c333c1bbbbbbbcccccddbcc.
............c333c11bbbbbccccccbbcc..
...........cc331c11bbbbccccccfbccf..
...........cc13c21cbbbcccccbbcfccf..
...........c111111cbbbfdddddc.fbbcf.
............cc1111fbdbbfdddc...fbbf.
..............cccfffbdbbfcc.....fbbf
....................fffff........fff
`, img`
....................................
....................................
....................................
...............ccffff...............
..............cddbbbf...............
.......ffffffcddbbbf................
.....ffbbbbbbbbbbbbbcfff.......ccccc
...ffbbbbbbbbcbcbbbbbcccff....cdbbbc
..fbbbbbbbbbbcbbcbbbbcccccfffcddbbc.
.fbcbbbbbbbbbbcbcbbbbccccccccbdbbf..
.fbbbbbbbfffbbcbbbbbccccccccccbbcf..
.ffbb111122fbbcbbbbcccccccbcffbccf..
..ff111111111bbbbccccccbbbcc..fbbcf.
....ccccccc111bdbbbfddbccc.....ffbbf
........ccccccfbdbbbfcc..........fff
...............ffffff...............
`];
            case "SR":
            case "anim7":return [img`
..............fffcc.............
..............fcbddcc...........
...............fbbddcc..........
...............fcbbccf..........
..ccc.........ffccccccfffff.....
..cbbcc....fffcbbbbcbbbbbbbff...
...cbbdc.ffcccbbbbcbcbbbbbbbbf..
...fbbdcfcccccbbbcbcbbffbbbbbbff
....fbbffcccccbbbbbcb1f211bbbcbf
....fcbbcccccccbbbbb11111111bbbf
....fcccccccccccbbbb11cc33111bf.
...fcbbffbdbcccccbbb112c13cccf..
...fbbf..ccddddcfbbbc111c31cf...
..fbbf.....ccdccbbdbf111cccf....
..fff........ccbbdcfcccc........
..............fffff.............
`, img`
..............fffcc.............
..............fbbddc............
...............fbbddc...........
ccc............fcbbccf..........
cbbcc.........ffccccccffffff....
.cbbdc.....fffcbbbbbbbbbbbbbff..
.fbbddc..ffcccbbbbcbcbbbbbbbbbff
..fbbdfffcccccbbbcbcbbffbbbbbcbf
..fcbbbcccccccbbbcbcb1f21111bbbf
..fccbcccccccccbbbbbb11111111bf.
.fcbbfffccccccccbbbb11cc33cccf..
.fbbf...cbdbcccccbbb111c131cf...
fbbf.....ccdddddfbbbc111c33f....
fff........ccddfbbdbf1111ff.....
.............cfbbdbfccccc.......
..............fffff.............
`, img`
..............fffc..............
..............fbddcc............
..ccc.........ffbddbc...........
..cbbc.........fcbbccf..........
...cbdc.......ffccccccfffffff...
...fbdc....fffcbbbbbbbbbbbbbcff.
....fbdc.ffcccbbbbbbcbbbbbbbbbcf
....fcdffcccccbbbcbcbbbffbbbbcbf
....fcbbccccccbbbcbcbbbf21111bbf
...fcbbccccccccbbbcbb11111111bf.
...fbbfffcccccccbbbb11bc33cccf..
..fbbf..cbdbcccccbbb111c131cf...
..fff....cbdddddccbbc112c33f....
..........ccbddccbbdf1111ff.....
............ccfbbbdfccccc.......
..............fffff.............
`, img`
..............fffcc.............
..............fbbddc............
...............fbbddc...........
ccc............fcbbccf..........
cbbcc.........ffccccccffffff....
.cbbdc.....fffcbbbbbbbbbbbbbff..
.fbbddc..ffcccbbbbcbcbbbbbbbbbff
..fbbdfffcccccbbbcbcbbffbbbbbcbf
..fcbbbcccccccbbbcbcb1f21111bbbf
..fccbcccccccccbbbbbb11111111bf.
.fcbbfffccccccccbbbb11cc33cccf..
.fbbf...cbdbcccccbbb111c131cf...
fbbf.....ccdddddfbbbc112c33f....
fff........ccddfbbdbf1111ff.....
.............cfbbdbfccccc.......
..............fffff.............
`];
            case "SAR":
            case "anim9":return [img`
..............fffcc.................
..............fbbddc................
...............fbbddc...............
ccc............fcbbccf..............
cbbcc.........ffccccccffffff........
.cbbdc.....fffcbbbbbbbbbbbbbff......
.fbbddc..ffcccbbbbcbcbbbbbbbbbff....
..fbbdfffcccccbbbcbcbbffbbbbbcbf....
..fcbbbcccccccbbbcbcb1f21111bbbf....
..fccbcccccccccbbbbbb11111111bf.....
.fcbbfffccccccccbbbb11cc33cccf......
.fbbf...cbdbcccccbbb111c131cf.......
fbbf.....ccdddddfbbbc112c33f........
fff........ccddfbbdbf1111ff.........
.............cfbbdbfccccc...........
..............fffff.................
`, img`
..............fffcc.................
..............fbbddc................
...............fbbddc...............
...............fcbbccffffff.........
..............ffcccbbbbbbbbfff......
ccccc......fffcbbbbbbbbbbbbbbbf.....
cbbbdc...ffcccbbbbcbcbffbbbbbcb.....
.cbbddcffcccccbbbcbcbbf21111bbb.....
..fbbdbcccccccbbbcbcb11111111bf.....
..fcbbcccccccccbbbbbb11c33cccf......
..fccbffccccccccbbbb11cc131cf.......
.fcbbf..cbdbcccccbbb1112c33f........
.fbbf....ccdddddfbbbc1111ff.........
fbbf.......ccddfbbdbf1ccc...........
fff..........cfbbdbfcc..............
..............fffff.................
`, img`
.............fffcc..................
.............fbbddc.................
..............fbbddfffffffff........
..............fcbcfbbbbbbbbbf.......
...........ffffccbbffb111cbbf.......
ccccc....ffcccbbbbbf2111111bf.......
cbbbdc..fccccbbcbcbb1133cc1f........
.cbbddcfcccccbcbcbbb1c131ccf........
..fbbdbccccccbcbcbbb121111f.........
..fcbbccccccccbbbbb1111111f.........
..fccbffcccccccbbbb111111f..........
.fcbbf.cbdbcccccbbbc1111c...........
.fbbf...cddddddfbbbc11cc............
fbbf.....ccdddfbbdbffc..............
fff........ccfbbdbf.................
.............fffff..................
`, img`
...........fffcc....................
...........fbbbbcfffffffff..........
............fbfffbbbbbbbbbf.........
............ffbbbbffb111bbf.........
..........ffcbbbbbf211111bf.........
.........fcccbcbcbb11cccc1f.........
ccccc...fcccbcbcbbb1c1c1cf..........
cbbddccfccccbcbcbbb1333c............
.ccbddbcccccbbbbbbb1c333c...........
..ccbbcccccccbbbbb11c133c...........
..fccbffccccccbbbb112c31cc..........
..fccf.cbbcccccbbbc111111c..........
.fcbbf..cdddddfbbbc1111cc...........
.fbbf....cdddfbbdbffccc.............
fbbf......ccfbbdbf..................
fff.........fffff...................
`, img`
..........fffcc...fffffff...........
..........fbbbbcffbbbbbbbf..........
...........fbffbbbbb111bbf..........
...........ffbbbbff11111bf..........
.........ffcbbbbbf21cccc1f..........
........fcccbcbcbb1c1c1cff..........
ccccc..fcccbcbcbbb1333ccf...........
cbbddcfccccbcbcbbb1c333c............
.ccbddcccccbbbbbbb1c333c............
..ccbbccccccbbbbb11c333c............
..fccbfccccccbbbb11c133cc...........
..fccfcbbcccccbbbc12c31cc...........
.fcbbf.cdddddfbbbc111111c...........
.fbbf...cdddfbbdbf1111cc............
fbbf.....ccfbbdbfffccc..............
fff........fffff....................
`, img`
....................................
....................................
....................................
...............ffffcc...............
...............fbbbddc..............
................fbbbddcffffff.......
ccccc.......fffcbbbbbbbbbbbbbff.....
cbbbdc....ffcccbbbbbcbcbbbbbbbbff...
.cbbddcfffcccccbbbbcbbcbbbbbbbbbbf..
..fbbdbccccccccbbbbcbcbbbbbbbbbbcbf.
..fcbbccccccccccbbbbbcbbfffbbbbbbbf.
..fccbffcbcccccccbbbbcbbf221111bbff.
.fcbbf..ccbbbccccccbbbb111111111ff..
fbbff.....cccbddfbbbdb111ccccccc....
fff..........ccfbbbdbfcccccc........
...............ffffff...............
`];
            case "Danh trai":
            case "anim11":return [img`
..............bbbbbb....
.............bcbdddbbb..
............bcccbddddbb.
.......cc...bddddbbdddb.
.......cdc.bdccccddbbbb.
.......cddcbcdbbbbcccdb.
........cddcbb111bbbbbbb
.........cddc144fbe441bb
..........cdc1ddf14d411b
..........cccd1ddd4111b.
...........1dd4144118b..
............1144dddd8...
.............8d1dddd8...
.............85544448...
..............888888....
................888.....
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
..............bbb.......
.............bcbbbbb....
...........bbccdddddbb..
..........bbcccddddddbb.
..........bddddbbbddddb.
.........bdccccdddbbbbb.
.........bcdbbbbbcccdbbb
..cc.....bbb111bbbbbbbbb
..cdcc...b1144fbb1441b1b
..ccddcc..b1ddfbb4d411b.
....cdddc11bddddd4111b..
.....ccdcdd11ddddddd8...
......cccdd4415444448...
.........111188888888...
.............88...888...
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
..............bbbbbb....
.............bbcbbbbbb..
............bbcbddddbbb.
.......cc..bbccbdddddbb.
.......cdc.bddddbbddddb.
.......cddbdccccddbbbbb.
........cdbcdbbbbccccbbb
.........cbbb111bbbbbbbb
..........b1144fb1441b1b
..........cb1ddfb4d411b.
..........c111ddd4111b..
....ccccccc1dd11dddd8...
.....dddddc1dd4414448...
......ccccc.111188888...
..........c...88888888..
...............8888888..
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
..............bbbbbb....
.............bdbccccbb..
............bdddbccccbb.
............bccccbbcccb.
...........bcddddccbbbb.
...........bdcbbbbdddcb.
...........bbbcccbbbbbbb
...........b1144fb1441bb
............b1ddf14d411b
.............bdddd4111b.
.............b14441ddb..
.............cccdd1ddb..
.............cdcddb11...
............cddc44448...
...........cddc88888....
..........cddc..888.....
..........cdc...........
..........cc............
........................
........................
........................
........................
........................
........................
`];
            case "Danh phai":
            case "anim12":return [img`
....bbbbbb..............
..bbbdddbcb.............
.bbddddbcccb............
.bdddbbddddb...cc.......
.bbbbddccccdb.cdc.......
.bdcccbbbbdcbcddc.......
bbbbbbb111bbcddc........
bb144ebf441cddc.........
b114d41fdd1cdc..........
.b1114ddd1dccc..........
..b8114414dd1...........
...8dddd4411............
...8dddd1d8.............
...84444558.............
....888888..............
.....888................
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
.......bbb..............
....bbbbbcb.............
..bbdddddccbb...........
.bbddddddcccbb..........
.bddddbbbddddb..........
.bbbbbdddccccdb.........
bbbdcccbbbbbdcb.........
bbbbbbbbb111bbb.....cc..
b1b1441bbf4411b...ccdc..
.b114d4bbfdd1b..ccddcc..
..b1114dddddb11cdddc....
...8ddddddd11ddcdcc.....
...8444445144ddccc......
...888888881111.........
...888...88.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
.......bb...............
....bbbbcbb.............
..bbddddbcbb............
.bbdddddbccbb...........
.bddddbbddddb...........
.bbbbbddccccdb..........
bbbccccbbbbdcb..........
bbbbbbbb111bbb..........
b1b1441bf4411b..........
.b114d4bfdd1b...........
..b1114ddd11.c..........
...8dddd11dd1ccccccc....
...8444144dd1cddddd.....
...888881111.ccccc......
..88888888...c..........
..888..88...............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
....bbbbbb..............
..bbccccbdb.............
.bbccccbdddb............
.bcccbbccccb............
.bbbbccddddcb...........
.bcdddbbbbcdb...........
bbbbbbbcccbbb...........
bb1441bf4411b...........
b114d41fdd1b............
.b1114ddddb.............
..bdd14441b.............
..bdd1ddccc.............
...11bddcdc.............
...84444cddc............
....88888cddc...........
.....888..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`];
            case "Soldier Animation":
            case "anim5":return [img`
. . . . . . d d d d . . . . . . 
. . . . d d d 2 2 d d d . . . . 
. . . d d d 2 2 2 2 d d d . . . 
. . d d d 1 1 1 1 1 1 d d d . . 
. . d d 1 2 2 2 2 2 2 1 1 d . . 
. . d 1 2 d d d d d d 2 1 d . . 
. . d d d d 1 1 1 1 d d d d . . 
. d d 1 d b f 4 4 f b d 1 d d . 
. d 1 1 4 1 f d d f 1 4 1 1 d . 
. . d 1 1 d d d d d d 1 1 d . . 
. . . d 1 1 4 4 4 4 1 1 d . . . 
. . 1 4 6 b b b b b b 6 4 1 . . 
. . 4 d 6 b b b b b b 6 d 4 . . 
. . 4 4 6 4 4 5 5 4 4 6 4 4 . . 
. . . . . 6 6 6 6 6 6 . . . . . 
. . . . . 6 6 . . 6 6 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . d d d d . . . . . . 
. . . . d d d 2 2 d d d . . . . 
. . . d d d 2 2 2 2 d d d . . . 
. . d d d 1 1 1 1 1 1 d d d . . 
. . d d 1 2 2 2 2 2 2 1 1 d . . 
. d d 1 2 d d d d d d 2 1 d d . 
. d d d d d 1 1 1 1 d d d d d . 
. . d 1 d b f 4 4 f b d 1 d . . 
. . d 1 4 1 f d d f 1 4 1 d . . 
. . . 6 1 4 d d d d 4 1 f 1 . . 
. . 6 1 6 c c c c 1 d d 4 1 . . 
. . 1 4 6 c c c c 1 d d 1 . . . 
. . . . 6 4 4 5 5 6 1 1 . . . . 
. . . . 6 6 6 6 6 6 6 . . . . . 
. . . . 6 6 6 . . . . . . . . . 
`, img`
. . . . . . d d d d . . . . . . 
. . . . d d d 2 2 d d d . . . . 
. . . d d d 2 2 2 2 d d d . . . 
. . d d d 1 1 1 1 1 1 d d d . . 
. . d d 1 2 2 2 2 2 2 1 1 d . . 
. . d 1 2 d d d d d d 2 1 d . . 
. . d d d d 1 1 1 1 d d d d . . 
. d d 1 d b f 4 4 f b d 1 d d . 
. d 1 1 4 1 f d d f 1 4 1 1 d . 
. . d 1 1 d d d d d d 1 1 d . . 
. . . d 1 1 4 4 4 4 1 1 d . . . 
. . 1 4 6 b b b b b b 6 4 1 . . 
. . 4 d 6 b b b b b b 6 d 4 . . 
. . 4 4 6 4 4 5 5 4 4 6 4 4 . . 
. . . . . 6 6 6 6 6 6 . . . . . 
. . . . . 6 6 . . 6 6 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . d d d d . . . . . . 
. . . . d d d 2 2 d d d . . . . 
. . . d d d 2 2 2 2 d d d . . . 
. . d d d 1 1 1 1 1 1 d d d . . 
. . d 1 1 2 2 2 2 2 2 1 d d . . 
. d d 1 2 d d d d d d 2 1 d d . 
. d d d d d 1 1 1 1 d d d d d . 
. . d 1 d b f 4 4 f b d 1 d . . 
. . d 1 4 1 f d d f 1 4 1 d . . 
. . 1 d 1 4 d d d d 4 1 6 . . . 
. . 1 4 d d 1 b b b b 6 1 6 . . 
. . . 1 d d 1 b b b b 6 4 1 . . 
. . . . 1 1 6 5 5 4 4 6 . . . . 
. . . . . 6 6 6 6 6 6 6 . . . . 
. . . . . . . . . 6 6 6 . . . . 
`];
            case "Back Soldier Animation":
            case "anim10":return [img`
. . . . . . d d d d . . . . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . d 1 1 1 d d 1 1 1 d . . . 
. . d d d d d 2 2 d d d d d . . 
. . d d 1 2 1 2 2 1 2 1 d d . . 
. . d 1 2 d 2 d d 2 d 2 1 d . . 
. . d d d 2 2 1 1 2 2 d d d . . 
. d d 1 d 2 d 1 1 d 2 d 1 d d . 
. d 1 1 d d 1 1 1 1 d 1 1 1 d . 
. . d 1 1 1 1 1 1 1 1 1 1 d . . 
. . . d 1 1 1 1 1 1 1 1 d . . . 
. . e 4 6 6 6 6 6 6 6 6 4 e . . 
. . 4 d 6 b b b b b b 6 d 4 . . 
. . 4 4 6 4 4 4 4 4 4 6 4 4 . . 
. . . . . 6 6 6 6 6 6 . . . . . 
. . . . . 6 6 . . 6 6 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . d d d d . . . . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . d 1 1 1 d d 1 1 1 d . . . 
. . . d d d d 2 2 d d d d . . . 
. . d d 1 2 1 2 2 1 2 1 d d . . 
. . d 1 2 d 2 d d d 2 d 1 d . . 
. . d d d 2 d 1 1 2 2 d d d . . 
. . d 1 2 d d 1 1 2 d 1 1 d . . 
. d d 1 d d 1 1 1 d 1 1 1 d d . 
. d d 1 1 1 1 1 1 1 1 1 1 d d . 
. . . d 1 1 1 1 1 1 1 1 d . . . 
. . . 1 6 6 6 6 6 6 6 6 4 1 . . 
. . . 4 6 b b b b b 1 d d 4 . . 
. . . 1 6 6 6 6 6 6 1 1 4 . . . 
. . . . 6 6 6 . . . . . . . . . 
`, img`
. . . . . . d d d d . . . . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . d 1 1 1 d d 1 1 1 d . . . 
. . d d d d d 2 2 d d d d d . . 
. . d d 1 2 1 2 2 1 2 1 d d . . 
. . d 1 2 d 2 d d 2 d 2 1 d . . 
. . d d d 2 2 1 1 2 2 d d d . . 
. d d 1 d 2 d 1 1 d 2 d 1 d d . 
. d 1 1 d d 1 1 1 1 d 1 1 1 d . 
. . d 1 1 1 1 1 1 1 1 1 1 d . . 
. . . d 1 1 1 1 1 1 1 1 d . . . 
. . e 4 6 6 6 6 6 6 6 6 4 e . . 
. . 4 d 6 b b b b b b 6 d 4 . . 
. . 4 4 6 4 4 4 4 4 4 6 4 4 . . 
. . . . . 6 6 6 6 6 6 . . . . . 
. . . . . 6 6 . . 6 6 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . d d d d . . . . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . d 1 1 1 d d 1 1 1 d . . . 
. . . d d d d 2 2 d d d d . . . 
. . d d 1 2 1 2 2 1 2 1 d d . . 
. . d 1 d 2 d d d 2 d 2 1 d . . 
. . d d d 2 2 1 1 d 2 d d d . . 
. . d 1 1 d 2 1 1 d d 2 1 d . . 
. d d 1 1 1 d 1 1 1 d d 1 d d . 
. d d 1 1 1 1 1 1 1 1 1 1 d d . 
. . . d 1 1 1 1 1 1 1 1 d . . . 
. . 1 4 6 6 6 6 6 6 6 6 1 . . . 
. . 4 d d 1 b b b b b 6 4 . . . 
. . . 4 1 1 6 6 6 6 6 6 1 . . . 
. . . . . . . . . 6 6 6 . . . . 
`];
            case "Eye Animation":
            case "anim16":return [img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........fffffffffff..........
........f11222222211f.........
.......f1122222222211f........
......f112225555522211f.......
.....f111225ff555522111f......
....f1111225ff5555221111f.....
....f1111225555555221111f.....
.....f11112255555221111f......
......f111122555221111f.......
.......f1111222221111f........
........f11111111111f.........
.........fffffffffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........fffffffffff..........
........f11222222211f.........
.......f1122222222211f........
......f112225555522211f.......
.....f11122555555522111f......
....f11112255ff555221111f.....
....f11112255ff555221111f.....
.....f11112255555221111f......
......f111122555221111f.......
.......f1111222221111f........
........f11111111111f.........
.........fffffffffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........fffffffffff..........
........f11222222211f.........
.......f1122222222211f........
......f112225555522211f.......
.....f111225555ff522111f......
....f1111225555ff5221111f.....
....f1111225555555221111f.....
.....f11112255555221111f......
......f111122555221111f.......
.......f1111222221111f........
........f11111111111f.........
.........fffffffffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`];
            case "Right Gun":
            case "anim14":return [img`
....bbbbbb..............
..bbbdddbcb.............
.bbddddbcccb............
.bdddbbddddb............
.bbbbddccccdb...........
.bdcccbbbbdcb...........
bbbbbbb111bb............
bb144ebf441...cccccc....
b114d41fdd1..cc11111c...
.b1114ddd1d..c.dddcc....
..b8114414dd1ccccc......
...8dddd4411.c..........
...8dddd1d8..c..........
...84444558.............
....888888..............
.....888................
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
....bbbbbb..............
..bbbdddbcb.............
.bbddddbcccb............
.bdddbbddddb............
.bbbbddccccdb...........
.bdcccbbbbdcb...........
bbbbbbb111bb.ccccccc....
bb144ebf441.cc11111c....
b114d41fdd1.c.dddccc....
.b1114ddd1d..cccc.......
..b8114414dd1.c.........
...8dddd4411...c........
...8dddd1d8.............
...84444558.............
....888888..............
.....888................
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "Left Gun":
            case "anim13":return [img`
..............bbbbbb....
.............bcbdddbbb..
............bcccbddddbb.
............bddddbbdddb.
...........bdccccddbbbb.
...........bcdbbbbcccdb.
............bb111bbbbbbb
....cccccc...144fbe441bb
...c11111cc..1ddf14d411b
....ccddd.c..d1ddd4111b.
......ccccc1dd4144118b..
..........c.1144dddd8...
..........c..8d1dddd8...
.............85544448...
..............888888....
................888.....
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
..............bbbbbb....
.............bcbdddbbb..
............bcccbddddbb.
............bddddbbdddb.
...........bdccccddbbbb.
...........bcdbbbbcccdb.
....ccccccc.bb111bbbbbbb
....c11111cc.144fbe441bb
....cccddd.c.1ddf14d411b
.......cccc..d1ddd4111b.
.........c.1dd4144118b..
........c...1144dddd8...
.............8d1dddd8...
.............85544448...
..............888888....
................888.....
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "Cup Animation":
            case "anim15":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 5 5 . . 5 . . . 5 . . 5 5 . 
. . 5 9 5 5 9 5 . 5 9 5 5 9 5 . 
. . . 5 9 7 5 8 5 8 5 7 9 5 . . 
. . . . 5 9 7 5 8 5 7 9 5 . . . 
. . . . . 5 9 7 5 7 9 5 . . . . 
. . . . . 5 9 7 5 7 9 5 . . . . 
. . . . . 5 9 7 5 7 9 5 . . . . 
. . . . . . 5 9 7 9 5 . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . 5 5 5 5 5 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 5 5 . . 5 . . . 5 . . 5 5 . 
. . 5 6 5 5 6 5 . 5 6 5 5 6 5 . 
. . . 5 6 9 5 b 5 b 5 9 6 5 . . 
. . . . 5 6 9 5 b 5 9 6 5 . . . 
. . . . . 5 6 9 5 9 6 5 . . . . 
. . . . . 5 6 9 5 9 6 5 . . . . 
. . . . . 5 6 9 5 9 6 5 . . . . 
. . . . . . 5 6 9 6 5 . . . . . 
. . . . . . . 5 6 5 . . . . . . 
. . . . . . . 5 6 5 . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . 5 5 5 5 5 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 5 5 . . 5 . . . 5 . . 5 5 . 
. . 5 9 5 5 6 5 . 5 6 5 5 9 5 . 
. . . 5 9 6 7 b 7 b 7 6 9 5 . . 
. . . . 5 9 6 7 b 7 6 9 5 . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . 5 9 6 7 6 9 5 . . . . 
. . . . . . 5 9 6 9 5 . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . 5 9 5 . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . . . 5 . . . . . . . 
. . . . . . 5 5 5 5 5 . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
